# Generated by Django 3.1.4 on 2020-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_p_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctotal', models.IntegerField()),
                ('cactive', models.IntegerField()),
                ('cured', models.IntegerField()),
                ('death', models.IntegerField()),
            ],
        ),
    ]
