# Generated by Django 3.1.4 on 2020-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_cnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnews',
            name='cactive',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cnews',
            name='ctotal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cnews',
            name='cured',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cnews',
            name='death',
            field=models.CharField(max_length=100),
        ),
    ]
