# Generated by Django 3.1.4 on 2020-12-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20201203_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('ddep', models.IntegerField()),
                ('dmob', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitem', models.CharField(max_length=100)),
                ('fquantity', models.IntegerField()),
                ('fprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('mquantity', models.IntegerField()),
                ('mprice', models.IntegerField()),
            ],
        ),
    ]
