# Generated by Django 3.1.4 on 2020-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_care_food_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('ddep', models.CharField(max_length=100)),
                ('dmob', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='care',
        ),
    ]
