# Generated by Django 3.1.4 on 2020-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_auto_20201205_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamt', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
                ('cno', models.IntegerField()),
                ('expno', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
