# Generated by Django 3.1.4 on 2020-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
