# Generated by Django 3.1.4 on 2020-12-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_remove_food_fquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pamt',
        ),
    ]
