# Generated by Django 3.1.4 on 2020-12-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_remove_payment_pamt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cname',
        ),
    ]
