# Generated by Django 3.1.4 on 2020-12-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0013_remove_payment_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pamt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
