# Generated by Django 3.1.4 on 2020-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_auto_20201206_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fquantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
