# Generated by Django 3.1.4 on 2020-12-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0015_food_fquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='fquantity',
        ),
    ]
