# Generated by Django 3.1.4 on 2020-12-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_remove_food_fquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='mquantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='pname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='uname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
