# Generated by Django 3.1.4 on 2020-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_auto_20201206_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
