# Generated by Django 3.1.4 on 2020-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0018_doctor_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/pics'),
        ),
    ]
