# Generated by Django 3.1.4 on 2020-12-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0020_auto_20201207_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
