# Generated by Django 3.1.4 on 2020-12-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0021_medicine_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='u_name',
        ),
        migrations.AddField(
            model_name='u_reg',
            name='f_status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='u_reg',
            name='m_status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
