# Generated by Django 3.1.4 on 2020-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0022_auto_20201209_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_reg',
            name='f_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
