# Generated by Django 3.1.4 on 2020-12-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0024_auto_20201209_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
    ]
